### ISSUE TITLE
"Go to word" bug when there is no module for word

### ISSUE THREAD

**Issue by skinsshark** [Galooshi/atom-import-js#19]
when the cursor is over a variable that has a module, `cmd+shift+k` (keybinding for "go to word") works like a charm. 

however, if the cursor is over anything that does _not_ have a module to go to, the appropriate `No JS module found for ____` warning does appears, but a new blank window also decides to open (equivalent to a `cmd+shift+n` action).

- the same occurs when using the `Goto word under cursor` option in the Packages > ImportJS tab

this plugin is super great and handy, thanks!

**Comment by lencioni** [comment]
Thanks for the report! This sounds super annoying. I'm not sure when I'll have time to work on this, but I'd be happy to review a PR that fixes this issue.

That functionality starts right around here: https://github.com/Galooshi/atom-import-js/blob/d56ccd106eef8697c5a7836fd0f2bde19cfe2130/lib/import-js.js#L127
