### ISSUE TITLE
import word gets confused with syntax

### ISSUE THREAD

**Issue by hexsprite** [Galooshi/atom-import-js#24]
seems to have a problem with characters that come before and after a symbol. See image for example. This is latest version of Atom & Atom-import-js.

![image](https://user-images.githubusercontent.com/23538/30036731-b2ec6dea-916a-11e7-8227-511be37f8e91.png)

**Comment by trotzig** [comment]
Interesting, I haven't seen that before. I wonder if they changed something to introduce a bug here? This is the relevant code: https://github.com/Galooshi/atom-import-js/blob/2e47e808cc2d464442054841e9bbf8a83b162c8b/lib/import-js.js#L13

**Comment by hexsprite** [comment]
seems resolved by newer Atom

**Comment by trotzig** [comment]
Ah, glad you got that sorted!
