### ISSUE TITLE
when importing, atom hangs

### ISSUE THREAD

**Issue by macrozone** [Galooshi/atom-import-js#25]
I updated some packages and reinstalled watchman.

now, when i try to import with cmd+shift+i, atom sometimes hang and has to be killed :-(

using latest version 0.11.0

**Comment by trotzig** [comment]
Ouch. I wonder if this could be the same issue as #22? Do you happen to remember what packages you updated? @hexsprite had a theory about incompatible packages but couldn't isolate it to a single one. Perhaps if you list your updates (even from memory if there is no physical trace) we can work together to come up with an isolated reproduction case?

**Comment by macrozone** [comment]
@trotzig 

I updated nuclideand some other packages (i just hit update all). I had also some problems with react-native packager, so i needed to reinstall watchman. I therefore suspect it might have something to do with watchman. Can i disable watchman for importjs without uninstalling it?

I am also using flow-type.

**Comment by trotzig** [comment]
There might be a way to disable watchman for a specific directory, not sure. There's no way to do this through import-js configuration unfortunately.

**Comment by hexsprite** [comment]
@macrozone you could try to reproduce the problem with only atom-import-js and required deps loaded then re-add your plugins one by one until you find the issue ;)

**Comment by macrozone** [comment]
it works again after updating nuclide or after switching to atom-ide ;-)
