### ISSUE TITLE
Always adds require() instead of import statements, regardless of config

### ISSUE THREAD

**Issue by callumlocke** [Galooshi/atom-import-js#28]
This looks like a really useful module, but I can't get it working properly. When I run 'fix imports', it nearly always adds `const foo = require('foo')` statements. 

I tried setting it explicitly:

```js
module.exports = {
  declarationKeyword: 'import',
}
```

But it still doesn't work. I have just installed it now, so I should be on the latest version. What could I be doing wrong?

**Comment by callumlocke** [comment]
It turns out `shift-cmd-i` is the same keybinding used by `nuclide-format-js:organize-requires`, part of Atom-IDE, which attempts something very similar to import-js (but not as well) so I thought the problem was with this plugin.

I've disabled the `nuclide-format-js:organize-requires` keybinding and the problem is fixed.

**Comment by trotzig** [comment]
Thanks for tracking that down!

**Comment by lencioni** [comment]
Would you be open to submitting a PR that adds this info to our readme?
