### ISSUE TITLE
plugin doesn't see my .importjs.js file

### ISSUE THREAD

**Issue by jameh** [Galooshi/atom-import-js#29]
my config looks like this:

```js
module.exports = {
  declarationKeyword: 'import',
  environments: ['meteor', 'node'],
};
```

when I type "Meteor" in a .js file, and hit cmd+shift+j, it adds the line:

```js
const { Meteor } = require('meteor/meteor');
```

but what I want it to add is

```js
import { Meteor } from 'meteor/meteor';
```

**Comment by jameh** [comment]
I just noticed that the default config for this package is for `declarationKeyword` to be `require`, so I'm thinking the plugin just isn't picking up my `.importjs.js` config file... I have it in the root of my project folder.

**Comment by jameh** [comment]
So, I closed my project, went File->New Window, went File->Add Project Folder, and my problem is fixed.

**Comment by trotzig** [comment]
Thanks for following up!
