### ISSUE TITLE
"Goto word" always opens new window when running Atom in dev mode

### ISSUE THREAD

**Issue by nene** [Galooshi/atom-import-js#31]
I'm almost always running Atom in dev mode, as I'm using some packages that I'm also hacking on.

I checked the source code and seems like it should never open a new window: https://github.com/Galooshi/atom-import-js/blob/master/lib/import-js.js#L138

I tried various things:

- Restart the whole Atom
- Opening Atom in my current project dir on command line with `atom -d .`
- Opening Atom `atom -d` and then from it File -> Add Project Folder...

...but no success. Only when I switch Atom to non-dev mode will it open a new tab as expected.

**Comment by trotzig** [comment]
That's annoying. It sounds like a bug in Atom to me, although there might be some way we can workaround this. Any help here is appreciated, I don't have the bandwidth to look into this myself.
