### ISSUE TITLE
Option for adding import line without auto-sorting imports

### ISSUE THREAD

**Issue by efatsi** [Galooshi/atom-import-js#54]
I'm working on a project with a team that predominantly uses VSCode and the import sorting algorithms there differ than what this package implements. I peeked at the code with the intention of splitting off the import adding from the import sorting (and configuring that with an option on this package), but it looks like the functionality is passed off to the [`import-js`](https://github.com/galooshi/import-js) package.

My questions currently - is my goal possible? Does the `import-js` package support this (I haven't dug through that source code yet)?

Thanks!

**Comment by lencioni** [comment]
You should be able to configure import-js with the sortImports option. https://github.com/galooshi/import-js#sortimports

**Comment by efatsi** [comment]
Thanks, I'll hopefully find time for a patch here w/ that option
