### ISSUE TITLE
Doesn't work with ES6 rest spread operators

### ISSUE THREAD

**Issue by ozantabak** [Galooshi/atom-import-js#9]
Doesn't work on files where I use destructuring assignment operators.
Throws a parse error when I do "fix imports".

example code
let { name, surname, ...other } = this.props;

**Comment by trotzig** [comment]
Thanks for the report. I have a fix coming up. In the meantime, can you check if you are using any other es7 syntax that we should support? I want to avoid adding ones that aren't necessary (they might slow things down). 

https://github.com/babel/babylon#plugins

We might want to switch to reading .babelrc, but I'm unsure of the complexities involved with doing that.

**Comment by trotzig** [comment]
I ended up adding two more plugins that I think made sense: `decorators` & `classProperties`.

**Comment by trotzig** [comment]
I just pushed version 0.4.3 with this fix. Will you update and verify that things are working?

**Comment by lencioni** [comment]
Decorators and class properties proposals have not yet hit stage 3. We
should probably make them opt-in.

**Comment by trotzig** [comment]
I can't see any harm allowing them to be parsed though, can you? 🙂

**Comment by ozantabak** [comment]
Many thanks for quick fix!
I don't use any other es7 syntax, but this one is a very useful one when working with React props etc.
